### PR TITLE
Redesign Profile Layout

### PR DESCRIPTION
**Pull request by rufatiani**
Redesign Profile Layout

### CODE REVIEW

**Comment by ugwulo** [comment]
good job @rufatiani please add screenshots for your design output

**Comment by rufatiani** [comment]
> 
> 
> good job @rufatiani please add screenshots for your design output

Sure, here is the screen shoot
WhatsApp Image 2020-10-02 at 14 28 24

**Comment by ugwulo** [comment]
Impressive @rufatiani

**Comment by rufatiani** [comment]
> 
> 
> Impressive @rufatiani

Thank you..

**Pull request merged**
