### PR TITLE
Revamped UI Design of on-boarding page

### PR DESCRIPTION
**Pull request by theGeekyLad**
## Highlights
- Fixed build throwing an error at `holder.binding.rootView ...` in  `HomeFragment.java` under `onBindViewHolder()`, that `rootView` is has only `private` access - updated that to `holder.binding.getRoot ...`
- Added official Material Design dependencies and replaced existing `TextView`s, `EditText`s etc. with Material components
- Changed look and feel of `activity_onboading.xml` to match standards
  - Based on whether student or staff, edit fields are shown / hidden
  - Added validation to `btnVerify` in `OnboardingActivity.java` which is automatically disabled if `editRegNum` or `editStaffId` is empty
- Removed `textColor` from `activity_onboarding.xml` to fix issues in dark mode

### Light Mode
light

### Dark Mode
dark

### CODE REVIEW

**Review by ugwulo — APPROVED** [review]
It's recommended not to edit .idea files and the like @theGeekyLad 
Just incase

**Review by ugwulo — APPROVED** [review]

**Review by ugwulo — CHANGES_REQUESTED** [review]
There's a link to the contributors in the README.md 
which github updates automatically 
You might have to drop this file @theGeekyLad

**Comment by ugwulo** [comment]
Impressive @theGeekyLad kudos to you on a good job👍
Please do well to address the issue I pointed out

**Review by ugwulo — APPROVED** [review]
Good job @theGeekyLad  👌

**Comment by ugwulo** [comment]
@theGeekyLad it is also important to note that PRs should focus on a single issue.
Feel free to submit different PRs for other issues for easy tracking

**Comment by theGeekyLad** [comment]
Thanks a bunch for your review comments @ugwulo ! Helps a lot for a newbie like me indeed. Should I raise another PR with the udpated `README.md`?

**Comment by ugwulo** [comment]
Yea sure, do well to raise another PR @theGeekyLad

**Comment by theGeekyLad** [comment]
Also, is there a test reg. no. that I could use to sign in and check the other screens too?

**Comment by ugwulo** [comment]
Yes, here it is 18EH/0059/CS @theGeekyLad

**Comment by theGeekyLad** [comment]
Hey @ugwulo , thanks for the ID for testing. :smile: Also, I've dropped the unnecessary files. Is this PR good to go?

**Pull request merged**
