### PR TITLE
Redesign Course Item List

### PR DESCRIPTION
**Pull request by mmuhamadamirzaidi**

### CODE REVIEW

**Comment by ugwulo** [comment]
good job @mmuhamadamirzaidi 
you can as well add screenshots of the ui 
looks you changed Gradle settings too

**Comment by mmuhamadamirzaidi** [comment]
Sure @ugwulo

**Comment by mmuhamadamirzaidi** [comment]
IMG_20201002_021501
IMG_20201002_021534

**Comment by ugwulo** [comment]
Great @mmuhamadamirzaidi

**Comment by mmuhamadamirzaidi** [comment]
Thanks @ugwulo . If you dont mind, can also contribute to my project here [https://github.com/mmuhamadamirzaidi/Hacktoberfest/issues](https://github.com/mmuhamadamirzaidi/Hacktoberfest/issues)

**Comment by ugwulo** [comment]
Ok, I'll take a look

**Pull request merged**
